-- ============================================================
-- V1: Tạo bảng ban đầu
-- Flyway đặt tên file: V{version}__{description}.sql
-- Convention: V1, V2, V3... tăng dần, KHÔNG được sửa file đã chạy
-- ============================================================

CREATE TABLE IF NOT EXISTS categories (
    id          BIGINT         GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name        VARCHAR(100)   NOT NULL UNIQUE,
    description VARCHAR(500)
);

CREATE TABLE IF NOT EXISTS tags (
    id   BIGINT       GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name VARCHAR(50)  NOT NULL UNIQUE
);

CREATE TABLE IF NOT EXISTS items (
    id          BIGINT          GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name        VARCHAR(200)    NOT NULL,
    price       NUMERIC(15, 2)  NOT NULL CHECK (price > 0),
    stock       INTEGER         NOT NULL DEFAULT 0 CHECK (stock >= 0),
    version     BIGINT          NOT NULL DEFAULT 0,  -- optimistic locking
    category_id BIGINT          NOT NULL REFERENCES categories(id)
);

CREATE TABLE IF NOT EXISTS item_tags (
    item_id BIGINT NOT NULL REFERENCES items(id) ON DELETE CASCADE,
    tag_id  BIGINT NOT NULL REFERENCES tags(id)  ON DELETE CASCADE,
    PRIMARY KEY (item_id, tag_id)
);

-- Indexes
CREATE INDEX idx_items_category ON items(category_id);
CREATE INDEX idx_items_price    ON items(price);
