-- Phase 5: bảng users cho Spring Security
CREATE TABLE app_users (
    id       BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    username VARCHAR(50)  NOT NULL UNIQUE,
    password VARCHAR(255) NOT NULL,   -- BCrypt hash, luôn 60 ký tự
    role     VARCHAR(30)  NOT NULL    -- 'ROLE_USER' hoặc 'ROLE_ADMIN'
);

-- Seed: admin user với password = "admin123"
-- BCrypt hash tạo bởi: new BCryptPasswordEncoder().encode("admin123")
INSERT INTO app_users (username, password, role)
VALUES ('admin', '$2a$10$N9qo8uLOickgx2ZMRZoMyeIjZAgcfl7p92ldGxad68LJZdL17lhWy', 'ROLE_ADMIN');

-- Seed: regular user với password = "user123"
INSERT INTO app_users (username, password, role)
VALUES ('user', '$2a$10$GRLdNijSQMUvl/au9ofL.eDwmoohzzS7.rmNSJZ.0FxO/BTk2YgWS', 'ROLE_USER');
